language: python
python:
  - "3.4"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config

#deploy:
#  # deploy develop to the staging environment
#  - provider: script
#    script: scripts/deploy.sh staging
#    on:
#      branch: develop
#  # deploy master to production
#  - provider: script
#    script: scripts/deploy.sh production
#    on:
#      branch: master

