- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer
      from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim

- alias: 'Licht aan bij thuiskomst'
  trigger:
    platform: zone
    entity_id: device_tracker.makzdot_maxiphone6
    zone: zone.home
    event: enter
  condition:
    condition: sun
    after: sunset
    after_offset: "-2:00:00"
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

- alias: 'Away'
  trigger:
    - platform: zone
      entity_id: device_tracker.makzdot_maxiphone6
      zone: zone.home
      event: leave
  action:
    service: scene.turn_on
    entity_id: scene.away

- alias: 'Licht aan voor schoonmaker'
  trigger:
    platform: state
    entity_id: device_tracker.4c21d01b63fc
    to: 'home'
  condition:
    condition: time
    after: "09:00:00"
    before: "17:30:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
      service: scene.turn_on
      entity_id: scene.schoonmaken