homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

frontend:
  themes: !include_dir_merge_named themes

ios:

logger:
  default: warning

config:

http:
  server_host: ::0
  api_password: !secret http_api_password
  base_url: home.makznet.nl
  use_x_forwarded_for: true
  trusted_proxies:
    - 2001:610:0:800f::/64
  login_attempts_threshold: 20
  ip_ban_enabled: True

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password

homekit:
  auto_start: False
  filter:
    include_domains:
      - light
      - switch
      - climate

updater:

discovery:

conversation:

history:

recorder:
  purge_keep_days: 365

logbook:

map:

sun:

sensor:
  - platform: moon
  - platform: time_date
  - platform: plex
    host: !secret plex_host
    token: !secret plex_token
    server: MaxFlix
    include_non_clients: true
  - platform: buienradar
    latitude: !secret latitude
    longitude: !secret longitude
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure
      - winddirection
      - windazimuth
      - windgust
      - precipitation

weather:
  - platform: darksky
    api_key: 01bd73236d2f8e8b45bb6e3f1f1fb291

device_tracker:
  - platform: snmp
    host: !secret snmp_host
    community: !secret snmp_community
    baseoid: .1.3.6.1.2.1.4.22.1.2.3
    #track_new_devices: false
  - platform: bluetooth_tracker

proximity:
  home:
    ignored_zones:
      - mam
    devices:
      - device_tracker.rikkert_rikki
      - device_tracker.makzdot_max
    tolerance: 100
    unit_of_measurement: m

tts:
  - platform: google
    language: 'nl'

apple_tv:
  - host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    name: AppleTV Woonkamer
    start_off: 1
    credentials: apple_tv_credentials

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: samsungtv
    host: 192.168.1.10
    name: Woonkamer TV
  - platform: plex
    entity_namespace: 'plex'
    use_episode_art: true
    include_non_clients: true
    use_custom_entity_ids: true

ffmpeg:

camera:
  - platform: foscam
    name: woonkamer-cam
    ip: woonkamer-ipcam.makz.lan
    username: !secret foscam_username
    password: !secret foscam_password

rfxtrx:
  device: /dev/ttyUSB0
  debug: False

owntracks:

mqtt:
  broker: 192.168.1.5
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

cloud:

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
script: !include scripts.yaml
zone: !include_dir_list zones
light: !include lights.yaml
switch: !include switches.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
scene: !include_dir_list scenes
alert: !include_dir_merge_named alerts/
binary_sensor: !include binary_sensors.yaml