homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  base_url: home.makznet.nl
  use_x_forwarded_for: True
  login_attempts_threshold: 3
  ip_ban_enabled: True

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password

homekit:
  pincode: !secret homekit_pin

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: moon
  - platform: time_date
  - platform: plex
    host: !secret plex_host
    token: !secret plex_token
    server: MaxFlix
  - platform: buienradar
    latitude: !secret latitude
    longitude: !secret longitude
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure
      - winddirection
      - windazimuth
      - windgust
      - precipitation

binary_sensor:
  - platform: workday
    country: NL

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

# Text to speech
tts:
  - platform: google

# Apple TV config
apple_tv:
  - host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    name: AppleTV Woonkamer
    start_off: 1
    credentials: apple_tv_credentials

# Klik aan klik Uit hub
rfxtrx:
  device: /dev/ttyUSB0
  debug: False

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'operation_mode'
      - 'temperature'
      - 'target'
      - 'hvac_state'
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'

# MQTT server config
mqtt:
  broker: 172.17.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include_dir_list zones
light: !include lights.yaml
switch: !include switches.yaml
zone: !include_dir_list zones
scene: !include_dir_list scenes

