homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key
    latitude: !secret latitude
    longitude: !secret longitude

upnp:
  port_mapping: false

# Enables the frontend
frontend:

# Enables the iOS component
ios:

#Enable config panel
config:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  login_attempts_threshold: 3
  ip_ban_enabled: True
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Enable suport for logging to influxdb
influxdb:
  host: rogue.makz.lan

# View all events in a logbook
logbook:

# Track the sun
sun:

# Telegram notifications
# notify:
#   - name: telegram
#     platform: telegram
#     api_key: !secret telegram_api_key
#     chat_id: !secret telegram_chat_id

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  discovery: true
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 150
    waypoints: True
    waypoint_whitelist:
      - makzdot
    track_new_devices: no
  - platform: snmp
    host: router.makz.lan
    community: !secret router_snmp_communicty
    baseoid: 1.3.6.1.2.1.4.22.1.2
    track_new_devices: no

rfxtrx:
  device: /dev/ttyUSB0
  debug: False

climate:
  platform: nest

camera:
#  - platform: synology
#    url: http://wolverine.makz.lan:5000
#    username: !secret synology_username
#    password: !secret synology_password
  - platform: foscam
    ip: 172.19.11.4
    username: !secret foscam_username
    password: !secret foscam_password


media_player:
  - platform: plex

apple_tv:
  - name: Woonkamer AppleTV
    host: 172.19.11.191
    login_id: !secret appletv_login_id
    start_off: true

# Text to speech
tts:
  - platform: google
    language: 'nl'

##Includes
zone: !include_dir_list zones
sensor: !include sensor.yaml
switch: !include switch.yaml
cover: !include cover.yaml
light: !include light.yaml
group: !include groups.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automation
script: !include_dir_named scripts
binary_sensor: !include binary_sensor.yaml
input_slider: !include input_slider.yaml
shell_command: !include shell_command.yaml
