homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key
    latitude: !secret latitude
    longitude: !secret longitude

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: rogue.makz.lan
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

device_tracker:
#  - platform: owntracks
#    max_gps_accuracy: 150
#    waypoints: True
  - platform: snmp
    host: pfsense.makz.lan
    community: !secret router_snmp_communicty
    baseoid: 1.3.6.1.2.1.4.22.1.2

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1EMJ0H-if00-port0
  debug: False

climate:
  platform: nest

camera:
  platform: foscam
  ip: ipcam-woonkamer.makz.lan
  name: Woonkamer
  port: 80
  username: !secret foscam_username
  password: !secret foscam_password

media_player:
  - platform: samsungtv
    host: 172.19.11.165
    port: 55000
    name: Woonkamer TV
    timeout: 2
  - platform: plex

# Text to speech
tts:
  platform: google

##Includes
zone: !include_dir_list zones
sensor: !include sensor.yaml
switch: !include switch.yaml
light: !include light.yaml
group: !include group.yaml
#scene: !include_dir_list scenes

