homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enable map
map:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  base_url: home.makznet.nl
  use_x_forwarded_for: True
  login_attempts_threshold: 3
  ip_ban_enabled: True

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Support for the iOS App
# ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_interval: 2
  purge_keep_days: 30

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password

# View all events in a logbook
logbook:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

# Weather Prediction
sensor:
  - platform: yr
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: travisci
    api_key: !secret travis_api_key
  - platform: plex
    host: !secret plex_host
    token: !secret plex_token
    server: MaxFlix

media_player:
  - platform: samsungtv
    host: 172.19.11.191
    name: Woonkamer TV
  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_api_key
  - platform: plex
    entity_namespace: plex
    show_all_controls: true
    use_episode_art: true

apple_tv:
  - host: !secret apple_tv_host
    name: AppleTV Woonkamer
    login_id: !secret apple_tv_login_id
    credentials: !secret apple_tv_credentials
    start_off: true

weather:
  - platform: buienradar
    latitude: !secret latitude
    longitude: !secret longitude

# Text to speech
tts:
  - platform: google
    language: nl

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'operation_mode'
      - 'temperature'
      - 'target'
      - 'hvac_state'
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'

camera:
  - platform: foscam
    name: Woonkamer camera
    ip: 172.19.11.243
    port: 80
    username: !secret foscam_username
    password: !secret foscam_password

rfxtrx:
  device: /dev/ttyUSB0
  debug: False

tradfri:

mqtt:
  broker: 172.17.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

device_tracker:
#  - platform: locative
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
  - platform: snmp
    host: !secret snmp_host
    community: !secret snmp_community
    baseoid: 1.3.6.1.2.1.4.22.1.2.3
    track_new_devices: yes

proximity:
  home:
    devices:
      - device_tracker.makzdot_a23689f5324a4084a5473386709c87eb
      - device_tracker.rikkert_rikki
  esther:
    devices:
      - device_tracker.makzdot_a23689f5324a4084a5473386709c87eb
      - device_tracker.rikkert_rikki
  surfnet:
    devices:
      - device_tracker.makzdot_a23689f5324a4084a5473386709c87eb
      - device_tracker.rikkert_rikki
  mam:
    devices:
      - device_tracker.makzdot_a23689f5324a4084a5473386709c87eb
      - device_tracker.rikkert_rikki

binary_sensor:
  - platform: workday
    country: NL

telegram_bot:
  - platform: broadcast
    api_key: 320539965:AAFh-sYMUSlq5hmo_mVNIGm9KasayDzeiiQ
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

group: !include groups.yaml
automation old: !include_dir_merge_list automation
automation: !include automations.yaml
light: !include lights.yaml
switch: !include switches.yaml
scene: !include_dir_list scenes
zone: !include_dir_list zones
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
