default_view:
  name: woonkamer
  view: yes
  icon: mdi:sofa
  entities:
    - group.scenes_woonkamer
    - climate.living_room_thermostaat
    - group.tradfri_keuken
    - group.tradfri_woonkamer
    - group.verlichting_woonkamer
    - group.led_strips_woonkamer
    - media_player.woonkamer_appletv
    - media_player.woonkamer_tv
    - camera.woonkamer_camera
    - group.schakelaars_woonkamer

Slaapkamers:
  name: Slaapkamers
  view: yes
  icon: mdi:hotel
  entities:
    - group.slaapkamer_max
    - group.slaapkamer_noeri
    - group.hal
    - group.verlichting_badkamer
    - group.wekker_max


media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - media_player.woonkamer_appletv_2
    - media_player.woonkamer_appletv
    - media_player.woonkamer_tv
    - media_player.emby__tvos__woonkamerappletv
    - group.all_remotes

weer:
  name: weer
  view: yes
  icon: mdi:weather-cloudy
  entities:
#    - group.buienradar
    - sensor.yr_symbol
    - weather.br_unknown_station
    - weather.openweathermap

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.personen
    - group.schoonmaak
    - group.devices
    - group.nest
    - group.nest_protect
    - group.batterij_status_tradfri
    - group.datum_en_tijd
    - group.all_devices

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.all_automations
    - group.all_scripts

alldevices:
  name: All Devices
  view: yes
  icon: mdi:infinity
  entities:
    - group.all_automations
    - group.all_devices
    - group.all_lights
    - group.sonoff_schakelaars
    - group.all_remotes
    - group.all_scripts
    - group.all_switches

##################################
# Sensors
##################################
Nest:
  icon: mdi:nest-thermostat
  entities:
    - sensor.living_room_thermostat_thermostaat_operation_mode
    - sensor.living_room_thermostat_thermostaat_hvac_state
    - sensor.living_room_thermostat_thermostaat_target
    - sensor.living_room_thermostat_thermostaat_temperature
    - sensor.living_room_thermostat_thermostaat_humidity
    - binary_sensor.living_room_thermostat_thermostaat_has_leaf
    - binary_sensor.living_room_thermostat_thermostaat_online
    - binary_sensor.living_room_thermostat_thermostaat_is_locked
    - binary_sensor.living_room_thermostat_thermostaat_is_using_emergency_heat
    - binary_sensor.living_room_thermostat_thermostaat_fan

Nest Protect:
  icon: mdi:nest-protect
  entities:
    - binary_sensor.hallway_nest_protect_online
    - sensor.hallway_nest_protect_battery_health
    - sensor.hallway_nest_protect_co_status
    - sensor.hallway_nest_protect_smoke_status

Batterij status tradfri:
  icon: mdi:battery-70
  entities:
    - sensor.afstandsbediening_hal
    - sensor.afstandsbediening_keukenlicht
    - sensor.afstandsbediening_woonkamer
    - sensor.afstandsbediening_noeri

Datum en tijd:
  icon: mdi:calendar-clock
  entities:
    - sensor.date
    - sensor.time
    - binary_sensor.workday_sensor
    - sun.sun
    - sensor.moon

Wekker Max:
  icon: mdi:calendar
  entities:
    - input_boolean.alarmstatus
    - input_boolean.alarmweekday
    - input_datetime.only_time

###################################
# Personen en Devices
###################################
Personen:
  entities:
    - device_tracker.makzdot_a23689f5324a4084a5473386709c87eb
    - device_tracker.a010818e6c32

Schoonmaak:
  entities:
    - device_tracker.1c232c46cb0d
    - device_tracker.9097f3588eb4
Devices:
  entities:
    - device_tracker.makzdot_456f498da3fe4abe8284f88867a4c8dc
    - device_tracker.makzdot_tablet_experiaz
    - device_tracker.acbc32cbfd29

###################################
# Lichtgroepen
###################################
Tradfri Keuken:
  entities:
    - light.keuken
    - light.keukenlamp_1
    - light.keukenlamp_2
    - light.keukenlamp_3
    - light.keukenlamp_4
    - light.keukenlamp_5
    - light.keukenlamp_6
    - light.keukenlamp_7
    - light.keukenlamp_8
Tradfri Woonkamer:
  entities:
    - light.plafonniere
    - light.woonkamer_1
    - light.woonkamer_2
    - light.woonkamer_3
    - light.woonkamer_4

Verlichting Woonkamer:
  entities:
    - light.eettafel
    - switch.sonoff_basic_076e52
    - switch.sonoff_basic_0742d9
    - switch.sonoff_basic_076a50
    - switch.sonoff_basic_1ca1ce

Led strips Woonkamer:
  entities:
    - light.h801_9950fc
    - light.h801_995008
    - light.h801_9950fb

Sonoff schakelaars:
  entities:
    - switch.sonoff_basic_0764b4
    - switch.sonoff_basic_076a50
    - switch.sonoff_basic_076e52
    - switch.sonoff_basic_1ca1ce
    - switch.sonoff_basic_0742d9

Verlichting Badkamer:
  entities:
    - switch.schakelaar_badkamer
    - switch.sonoff_badkamer

Scenes woonkamer:
  entities:
    - scene.livingroom_normal
    - scene.livingroom_dim
    - scene.schoonmaken
    - scene.alle_lichten_uit
    - scene.away

Schakelaars Woonkamer:
  entities:
    - light.plafonniere
    - light.keuken
    - switch.zonnescherm
    - switch.main_switch
    - switch.fluxer

Slaapkamer Max:
  entities:
    - light.plafoniere_max
    - light.schemerlamp_max

Slaapkamer Noeri:
  entities:
    - light.hanglamp_noeri
    - light.noeri
    - light.schemerlamp_noeri

Hal:
  entities:
    - switch.bewegingsensor_gang
    - light.hal
    - light.hallamp_1
    - light.hallamp_2
    - light.hallamp_3
    - light.hallamp_4
