##########################################
# Homepage en subpagina's
##########################################

default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.scenes
    - group.klimaatbeheersing_woonkamer
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_hal
    - group.verlichting_badkamer
    - group.mediaspelers_woonkamer
    - group.schakelaars_woonkamer

verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_hal
    - group.verlichting_badkamer

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.personen
    - group.overige_apparaten
    - group.schoonmaak
    - group.weer
    - group.nzbget

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.automations

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.mediaspelers_woonkamer
    - group.plex_server

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:
    - group.bewakingscameras_woonkamer

##########################################
# Groups verlichting per kamer
##########################################
Scenes:
  entities:
    - scene.livingroom_normal
    - scene.livingroom_dim
    - scene.alle_lichten_uit
    - scene.away
    - scene.schoonmaken

Verlichting Woonkamer:
  entities:
    - light.keuken
    - light.plafoniere
    - light.schemerlampen
    - light.switch1
    - light.eettafel

Schakelaars Woonkamer:
  - switch.main_switch
  - switch.zonnescherm
  - switch.fluxer
  - switch.sonoff_power

Klimaatbeheersing Woonkamer:
  entities:
    - climate.living_room_thermostaat
    - binary_sensor.living_room_thermostat_thermostaat_has_leaf
    - binary_sensor.living_room_thermostat_thermostaat_online
    - sensor.living_room_thermostat_thermostaat_hvac_state
    - binary_sensor.living_room_thermostat_thermostaat_is_locked

Verlichting Slaapkamer Max:
  entities:
    - light.plafoniere_max
    - light.schemerlamp_max

Verlichting Slaapkamer Noeri:
  entities:
    - light.hanglamp_noeri
    - light.schemerlamp_noeri

Verlichting Hal:
  entities:
    - light.hal

Verlichting Badkamer:
  entities:
    - light.badkamer

##########################################
# Groups Mediaspelers per kamer
##########################################
Mediaspelers Woonkamer:
  entities:
    - media_player.woonkamer_appletv
#    - media_player.woonkamer
    - media_player.woonkamer_tv



##########################################
# Groups bewakingscamera's per kamer
##########################################
bewakingscameras_woonkamer:
  name: "Bewakingscamera's Woonkamer"
  entities:
    - camera.ipcamwoonkamer
    - camera.foscam_camera


##########################################
# Groups device tracking
##########################################

personen:
  name: "Personen en apparaten"
  entities:
    - device_tracker.makzdot_maxiphone6
    - device_tracker.makzdot_rikki_telefoon
    - device_tracker.74a528a58562
    - device_tracker.74a528a5844b

Overige_apparaten:
  name: "Overige apparaten"
  entities:
    - device_tracker.makzdot_maxiphone5
    - device_tracker.experiaz_tablet_experiaz
    - device_tracker.acbc32cbfd29 #macbook max

schoonmaak:
  name: "Schoonmakers"
  entities:
    - device_tracker.74a528a58562
    - device_tracker.74a528a5844b

Alle apparaten:
  entities:
    - group.all_devices

Weer:
  entities:
    - weather.openweathermap
    - sensor.yr_symbol
    - sun.sun
    - sensor.moon

NZBget:
  entities:
    - sensor.nzbget_speed
    - sensor.nzbget_average_speed
    - sensor.nzbget_article_cache
    - sensor.nzbget_disk_free
    - sensor.nzbget_download_paused
    - sensor.nzbget_post_processing_paused
    - sensor.nzbget_queue_size
    - sensor.nzbget_size
    - sensor.nzbget_uptime

Speedtest:
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload

Plex server:
  entities:
    - sensor.plex_spy

Automations:
  entities:
    - automation.licht_aan_bij_thuiskomst
    - automation.licht_aan_in_de_avond
    - automation.licht_aan_met_afstandsbediening
    - automation.licht_uit_met_afstandsbediening
    - automation.licht_aan_voor_schoonmaker
    - automation.thermostaat_uit_away_mode_bij_thuiskomst
    - automation.media_player_playing_movie
    - automation.media_player_playing_tvshow
    - automation.media_player_playing_music
    - automation.media_player_pausedstopped
    - automation.away


