################################################
##         View                               ##
################################################
verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.scenes
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_hal
    - group.verlichting_badkamer

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:
    - group.bewakingscameras_woonkamer

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.mediaspelers_woonkamer
    - group.plex_server

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.licht_en_scenes
    - group.multimedia
    - group.device_tracker
    - group.klimaat
    - group.scripts

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.personen
    - group.overige_apparaten
    - group.schoonmaak
    - group.weer
    - group.nzbget
    - group.rookmelder_hal
    - group.batterylevels

weer:
  name: Weer
  view: yes
  icon: mdi:weather-partlycloudy
  entities:
    - group.weer_algemeen
    - group.dark_sky
    - group.open_weathermap

################################################
##         Sensore Groups                     ##
################################################
Weer Algemeen:
  entities:
    - sensor.time
    - sensor.yr_symbol
    - sun.sun
    - sensor.moon
    - binary_sensor.workday_sensor

Open weathermap:
  entities:
    - sensor.owm_cloud_coverage
    - sensor.owm_condition
    - sensor.owm_humidity
    - sensor.owm_pressure
    - sensor.owm_rain
    - sensor.owm_snow
    - sensor.owm_temperature
    - sensor.owm_wind_bearing
    - sensor.owm_wind_speed

Dark Sky:
  entities:
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_daily_high_apparent_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_apparent_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_dew_point
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_humidity
    - sensor.dark_sky_icon
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_nearest_storm_bearing
    - sensor.dark_sky_nearest_storm_distance
    - sensor.dark_sky_ozone
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_pressure
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_visibility
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_wind_speed

NZBget:
  entities:
    - sensor.nzbget_speed
    - sensor.nzbget_average_speed
    - sensor.nzbget_article_cache
    - sensor.nzbget_disk_free
    - sensor.nzbget_download_paused
    - sensor.nzbget_post_processing_paused
    - sensor.nzbget_queue_size
    - sensor.nzbget_size
    - sensor.nzbget_uptime

Rookmelder Hal:
  entities:
    - binary_sensor.hallway_nest_protect_online
    - sensor.hallway_nest_protect_battery_health
    - sensor.hallway_nest_protect_co_status
    - sensor.hallway_nest_protect_smoke_status

Klimaatbeheersing Woonkamer:
  entities:
    - climate.living_room_thermostaat
    - sensor.living_room_thermostat_thermostaat_humidity
    - binary_sensor.living_room_thermostat_thermostaat_has_leaf
    - binary_sensor.living_room_thermostat_thermostaat_online
    - sensor.living_room_thermostat_thermostaat_operation_mode
    - sensor.living_room_thermostat_thermostaat_hvac_state
    - binary_sensor.living_room_thermostat_thermostaat_is_locked
    - binary_sensor.living_room_thermostat_thermostaat_is_using_emergency_heat
    - binary_sensor.living_room_thermostat_thermostaat_fan
    - sensor.living_room_thermostat_thermostaat_humidity
    - sensor.living_room_thermostat_thermostaat_temperature
    - sensor.living_room_thermostat_thermostaat_target

Plex sensor:
  entities:
    - sensor.plex_spy

################################################
##         Device tracker Groups              ##
################################################
personen:
  name: "Personen en apparaten"
  entities:
    - device_tracker.makzdot_maxiphone6
    - device_tracker.makzdot_rikki_telefoon
#    - device_tracker.74a528a58562
#    - device_tracker.74a528a5844b

Overige_apparaten:
  name: "Overige apparaten"
  entities:
    - device_tracker.makzdot_maxiphone5
    - device_tracker.experiaz_tablet_experiaz
    - device_tracker.acbc32cbfd29 #macbook max
    - device_tracker.maxiphonesix
    - device_tracker.maxiphonefive

schoonmaak:
  name: "Schoonmakers"
  entities:
    - device_tracker.74a528a58562
    - device_tracker.74a528a5844b

Batterylevels:
  name: "Accu Niveaus"
  entities:
    - sensor.battery_maxiphone5
    - sensor.battery_maxiphone6
    - sensor.maxiphone_battery_level
    - sensor.maxiphone_battery_state
    - sensor.maxiphonesix_battery_level
    - sensor.maxiphonesix_battery_state
    - sensor.hallway_nest_protect_battery_health

################################################
##         Automation Groups                  ##
################################################
Timer light:
  entities:
    - input_slider.auto_light_minutes
    - input_slider.auto_light_duration
    - sensor.auto_light_duration
    - sensor.auto_light_minutes
    - sensor.auto_light_start
    - sensor.auto_light_stop
    - automation.auto_light_on
    - automation.auto_light_off

Multimedia:
  entities:
    - automation.appletv_aan_samen_met_tv
    - automation.appletv_uit_samen_met_tv
    - automation.media_player_playing_movie
    - automation.media_player_playing_tvshow
    - automation.media_player_playing_music
    - automation.media_player_pausedstopped

Klimaat:
  entities:
    - automation.thermostaat_uit_away_mode_bij_thuiskomst

Licht en Scenes:
  entities:
    - automation.licht_aan_bij_thuiskomst
    - automation.licht_aan_in_de_avond
    - automation.licht_aan_met_afstandsbediening
    - automation.licht_uit_met_afstandsbediening
    - automation.licht_aan_voor_schoonmaker
    - automation.away

Device tracker:
  entities:
    - automation.refresh_owntracks

Scripts:
  entities:
    - script.update_config
    - script.refresh_devices

################################################
##         Lighting groups                    ##
################################################
Scenes:
  entities:
    - scene.alle_lichten_uit
    - scene.away
    - scene.eettafel_effect
    - scene.livingroom_dim
    - scene.livingroom_normal
    - scene.schoonmaken

################################################
##         Lighting groups                    ##
################################################
Verlichting Woonkamer:
  entities:
    - light.keuken
    - light.plafoniere
    - light.schemerlampen
    - light.spots
    - light.eettafel
    - light.led_strip
    - light.led_strip_2

Verlichting Slaapkamer Max:
  entities:
    - light.plafoniere_max
    - light.schemerlamp_max

Verlichting Slaapkamer Noeri:
  entities:
    - light.hanglamp_noeri
    - light.schemerlamp_noeri

Verlichting Hal:
  entities:
    - light.hal

Verlichting Badkamer:
  entities:
    - light.badkamer

##########################################
# Groups Mediaspelers per kamer
##########################################
Mediaspelers Woonkamer:
  entities:
    - media_player.woonkamer_appletv
#    - media_player.woonkamer
    - media_player.woonkamer_tv

##########################################
# Groups bewakingscamera's per kamer
##########################################
bewakingscameras_woonkamer:
  name: "Bewakingscamera's Woonkamer"
  entities:
    - camera.foscam_camera
