##########################################
# Homepage en subpagina's
##########################################

#default_view:
#  view: yes
#  icon: mdi:home
#  entities:

verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.verlichting_woonkamer

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:

##########################################
# Groups verlichting per kamer
##########################################

Verlichting Woonkamer:
  - light.keuken
  - light.plafoniere
  - light.schemerlampen
  - switch.switch1
  - light.eettafel
