##########################################
# Homepage en subpagina's
##########################################

default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.personen
    - group.scenes
    - group.woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_badkamer
    - camera.ipcamwoonkamer
    - media_player.apple_tv
    - media_player.woonkamer_tv
    - media_player.woonkamer
    - updater.updater

verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_badkamer
    - group.scenes

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.weer
    - group.klimaat_woonkamer
    - group.personen
    - group.schoonmakers
    - group.alle_apparaten
    - group.all_tracked
    - group.devices
    - group.have_i_been_pwned
    - group.speedtest

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.automation_rules

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - sensor.plex_spy
    - media_player.apple_tv
    - media_player.woonkamer_tv
    - media_player.woonkamer
    - media_player.xperia_van_max
    - media_player.maxiphonesix

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:
    - camera.ipcamwoonkamer

##########################################
# Groepen (Tabellen op pagina's)
##########################################

Personen:
  - device_tracker.makzdot_maxiphone6

Schoonmakers:
  - device_tracker.74a528a5844b
  - device_tracker.74a528a58562

All tracked:
  - device_tracker.makzdot_maxiphone6
  - device_tracker.74a528a5844b
  - device_tracker.74a528a58562

Alle apparaten:
  - device_tracker.makzdot_maxiphone6
  - device_tracker.makzdot_maxiphone5
  - device_tracker.makzdot_tablet_max
  - device_tracker.acbc32cbfd29
  - device_tracker.74a528a5844b
  - device_tracker.74a528a58562

Devices:
  - sensor.battery_maxiphone6
  - sensor.battery_maxiphone5

Klimaat Woonkamer:
  - sensor.living_room_thermostat_thermostaat_temperature
  - sensor.living_room_thermostat_thermostaat_target
  - sensor.living_room_thermostat_thermostaat_humidity
  - sensor.living_room_thermostat_thermostaat_operation_mode
  - sensor.living_room_thermostat_thermostaat_hvac_state
  - binary_sensor.living_room_thermostat_thermostaat_online
  - binary_sensor.living_room_thermostat_thermostaat_has_leaf
  - binary_sensor.living_room_thermostat_thermostaat_is_using_emergency_heat
  - binary_sensor.living_room_thermostat_thermostaat_is_locked
  - binary_sensor.living_room_thermostat_thermostaat_fan

Weer:
  - sun.sun
  - sensor.yr_symbol
  - weather.openweathermap

Camera:
  - camera.woonkamer

Verlichting Woonkamer:
  - light.schemerlampen
  - light.keuken
  - light.plafoniere
  - switch.switch1
  - switch.main_switch
  - light.eettafel

Scenes:
  - scene.livingroom_normal
  - scene.livingroom_dim
  - scene.livingroom_dark_day
  - scene.schoonmaken
  - scene.away

Verlichting Slaapkamer Max:
  - light.plafoniere_max
  - light.schemerlamp_max 

Verlichting Slaapkamer Noeri:
  - light.schemerlamp_noeri
  - light.hanglamp_noeri

Verlichting Badkamer:
  - light.badkamer

Zonwering:
  - switch.zonnescherm

Automation rules:
  - automation.licht_aan_bij_thuiskomst
  - automation.licht_aan_in_de_avond
  - automation.licht_aan_voor_schoonmaker
  - automation.licht_uit_voor_schoonmaker
  - automation.media_player_playing
  - automation.media_player_pausedstopped
  - automation.away

Woonkamer:
  - climate.living_room_thermostaat
  - light.schemerlampen
  - light.keuken
  - light.plafoniere
  - light.eettafel
  - switch.switch1
  - switch.main_switch
  - switch.zonnescherm

Have I Been PWNED:
  - sensor.breaches_maxmuddegmailcom
  - sensor.breaches_makzdotoutlookcom
  - sensor.breaches_maxmuddesurfnetnl

Speedtest:
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.speedtest_ping
