##########################################
# Homepage en subpagina's
##########################################

#default_view:
#  view: yes
#  icon: mdi:home
#  entities:

verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_hal
    - group.verlichting_badkamer

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.mediaspelers_woonkamer

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:

##########################################
# Groups verlichting per kamer
##########################################

Verlichting Woonkamer:
  entities:
    - light.keuken
    - light.plafoniere
    - light.schemerlampen
    - switch.switch1
    - light.eettafel

Verlichting Slaapkamer Max:
  entities:
    - light.plafoniere_max
    - light.schemerlamp_max

Verlichting Slaapkamer Noeri:
  entities:
    - light.hanglamp_noeri
    - light.schemerlamp_noeri

Verlichting Hal:
  entities:
    - light.hal

Verlichting Badkamer:
  entities:
    - light.badkamer

Mediaspelers Woonkamer:
  entities:
    - media_player.apple_tv
    - media_player.woonkamer
    - media_player.woonkamer_tv

Climaat beheersing Woonkamer:
  entities:
    - climate.living_room_thermostaat
