##########################################
# Homepage en subpagina's
##########################################

#default_view:
#  view: yes
#  icon: mdi:home
#  entities:

verlichting:
  name: Verlichting
  view: yes
  icon: mdi:lightbulb-outline
  entities:
    - group.verlichting_woonkamer
    - group.verlichting_slaapkamer_max
    - group.verlichting_slaapkamer_noeri
    - group.verlichting_hal
    - group.verlichting_badkamer

sensors:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.personen
    - group.schoonmaak

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:

media:
  name: Media
  view: yes
  icon: mdi:play-circle-outline
  entities:
    - group.mediaspelers_woonkamer

cameras:
  name: Cameras
  view: yes
  icon: mdi:video
  entities:
    - group.bewakingscameras_woonkamer

##########################################
# Groups verlichting per kamer
##########################################

Verlichting Woonkamer:
  entities:
    - light.keuken
    - light.plafoniere
    - light.schemerlampen
    - switch.switch1
    - light.eettafel

Verlichting Slaapkamer Max:
  entities:
    - light.plafoniere_max
    - light.schemerlamp_max

Verlichting Slaapkamer Noeri:
  entities:
    - light.hanglamp_noeri
    - light.schemerlamp_noeri

Verlichting Hal:
  entities:
    - light.hal

Verlichting Badkamer:
  entities:
    - light.badkamer

##########################################
# Groups Mediaspelers per kamer
##########################################
Mediaspelers Woonkamer:
  entities:
    - media_player.apple_tv
    - media_player.woonkamer
    - media_player.woonkamer_tv

##########################################
# Groups klimaatbeheersing per kamer
##########################################
Klimaatbeheersing Woonkamer:
  entities:
    - climate.living_room_thermostaat
    - binary_sensor.living_room_thermostat_thermostaat_has_leaf
    - binary_sensor.living_room_thermostat_thermostaat_online
    - sensor.living_room_thermostat_thermostaat_hvac_state
    - binary_sensor.living_room_thermostat_thermostaat_is_locked


##########################################
# Groups bewakingscamera's per kamer
##########################################
bewakingscameras_woonkamer:
  name: "Bewakingscamera's Woonkamer"
  entities:
    - camera.ipcamwoonkamer

##########################################
# Groups device tracking
##########################################

personen:
  name: "Personen en apparaten"
  entities:
    - device_tracker.makzdot_maxiphone6
    - device_tracker.makzdot_maxiphone5
    - device_tracker.makzdot_tablet_max
    - device_tracker.acbc32cbfd29 #macbookpro max
    - device_tracker.makzdot_rikki_telefoon

schoonmaak:
  name: "Schoonmakers"
  entities:
    - device_tracker.74a528a58562
    - device_tracker.74a528a5844b
