#lifx lampen broadcast voor automatische discovery
- platform: lifx
  broadcast: 172.19.11.255

#klik aan klik uit verlichting
- platform: rfxtrx
  automatic_add: false
  devices:
    0b11000203f5682002000070:
      name: Keuken
    0b11000e011acf160e010f50:
      name: Schemerlampen
    0b110005011acf1602000070:
      name: Plafoniere
#    0b110004011acf1605010f70:
#      name: Schemerlamp Noeri
    0b110000011acf160f010f70:
      name: Hanglamp Noeri
#    0b11000b011acf1606000070:
#      name: Schemerlamp Max
    0b11000c011acf160d000070:
      name: Plafoniere Max
    0b1100010131a3ce0a010f60:
      name: Badkamer
    0b110036011acf1607010f70:
      name: Hal

- platform: mqtt
  name: "Schemerlamp Max"
  state_topic: "stat/sonoff-01/POWER"
  command_topic: "cmnd/sonoff-01/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Schemerlamp Noeri"
  state_topic: "stat/sonoff-02/POWER"
  command_topic: "cmnd/sonoff-02/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Spots"
  state_topic: "stat/sonoff-03/POWER"
  command_topic: "cmnd/sonoff-03/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt_json
  name: mqtt_json_light_1
  state_topic: "home/rgb1"
  command_topic: "home/rgb1/set"
  brightness: true
  rgb: true
  optimistic: false
  qos: 0
