- platform: lifx
  broadcast: 172.19.12.63

#klik aan klik uit verlichting
- platform: rfxtrx
  automatic_add: True
  devices:
    0b11000e011acf160e010f50:
      name: Schemerlamp Max

    0b110000011acf160f010f70:
      name: Schemerlamp Noeri

    0b110036011acf1607010f70:
      name: Plafoniere Max

    0b11000c011acf160d000070:
      name: hallamp 4

- platform : group
  name: Keukenverlichting groep 1
  entities:
    - light.keukenlamp_1
    - light.keukenlamp_2
    - light.keukenlamp_4
    - light.keukenlamp_6
    - light.keukenlamp_7
    - light.keukenlamp_8

- platform : group
  name: Keukenverlichting groep 2
  entities:
    - light.keukenlamp_3
    - light.keukenlamp_5

- platform : group
  name: Woonkamer groep 1
  entities:
    - light.woonkamer_2
    - light.woonkamer_3
    - light.woonkamer_4