#klik aan klik uit verlichting
- platform: rfxtrx
  automatic_add: false
  devices:
    0b11000e011acf160e010f50:
      name: Schemerlamp Max

    0b110000011acf160f010f70:
      name: Schemerlamp Noeri

    0b110036011acf1607010f70:
      name: Plafoniere Max

- platform: group
  name: Keukenverlichting groep 1
  entities:
    - light.keukenlamp_1
    - light.keukenlamp_2
    - light.keukenlamp_4
    - light.keukenlamp_6
    - light.keukenlamp_7
    - light.keukenlamp_8

- platform: group
  name: Keukenverlichting groep 2
  entities:
    - light.keukenlamp_3
    - light.keukenlamp_5

- platform: group
  name: Schemerlampen slaapkamers
  entities:
    - light.schemerlamp_noeri
    - light.schemerlamp_max

- platform: group
  name: Woonkamer groep 1
  entities:
    - light.woonkamer_2
    - light.woonkamer_3
    - light.woonkamer_4

- name: badkamer
  platform: mqtt
  state_topic: /home/light/badkamer/relay/0
  command_topic: /home/light/badkamer/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/badkamer/status
  payload_available: 1
  payload_not_available: 0

- name: woonkamer-ledstrip-tv
  platform: mqtt
  state_topic: /home/light/woonkamer-ledstrip-tv/relay/0
  command_topic: /home/light/woonkamer-ledstrip-tv/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-ledstrip-tv/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /home/light/woonkamer-ledstrip-tv/brightness
  brightness_command_topic: /home/light/woonkamer-ledstrip-tv/brightness/set
  rgb_state_topic: /home/light/woonkamer-ledstrip-tv/rgb
  rgb_command_topic: /home/light/woonkamer-ledstrip-tv/rgb/set
  color_temp_command_topic: /home/light/woonkamer-ledstrip-tv/mired/set
  white_value_state_topic: /home/light/woonkamer-ledstrip-tv/channel/3
  white_value_command_topic: /home/light/woonkamer-ledstrip-tv/channel/3/set

- name: woonkamer-ledstrip-tv-meubel
  platform: mqtt
  state_topic: /home/light/woonkamer-ledstrip-tv-meubel/relay/0
  command_topic: /home/light/woonkamer-ledstrip-tv-meubel/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-ledstrip-tv-meubel/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /home/light/woonkamer-ledstrip-tv-meubel/brightness
  brightness_command_topic: /home/light/woonkamer-ledstrip-tv-meubel/brightness/set
  rgb_state_topic: /home/light/woonkamer-ledstrip-tv-meubel/rgb
  rgb_command_topic: /home/light/woonkamer-ledstrip-tv-meubel/rgb/set
  color_temp_command_topic: /home/light/woonkamer-ledstrip-tv-meubel/mired/set
  white_value_state_topic: /home/light/woonkamer-ledstrip-tv-meubel/channel/3
  white_value_command_topic: /home/light/woonkamer-ledstrip-tv-meubel/channel/3/set

- name: woonkamer-ledstrip-3
  platform: mqtt
  state_topic: /home/light/woonkamer-ledstrip-3/relay/0
  command_topic: /home/light/woonkamer-ledstrip-3/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-ledstrip-3/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: /home/light/woonkamer-ledstrip-3/brightness
  brightness_command_topic: /home/light/woonkamer-ledstrip-3/brightness/set
  rgb_state_topic: /home/light/woonkamer-ledstrip-3/rgb
  rgb_command_topic: /home/light/woonkamer-ledstrip-3/rgb/set
  color_temp_command_topic: /home/light/woonkamer-ledstrip-3/mired/set
  white_value_state_topic: /home/light/woonkamer-ledstrip-3/channel/3
  white_value_command_topic: /home/light/woonkamer-ledstrip-3/channel/3/set

- name: woonkamer-schemerlamp-links
  platform: mqtt
  state_topic: /home/light/woonkamer-schemerlamp-links/relay/0
  command_topic: /home/light/woonkamer-schemerlamp-links/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-schemerlamp-links/status
  payload_available: 1
  payload_not_available: 0

- name: woonkamer-schemerlamp-rechts
  platform: mqtt
  state_topic: /home/light/woonkamer-schemerlamp-rechts/relay/0
  command_topic: /home/light/woonkamer-schemerlamp-rechts/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-schemerlamp-rechts/status
  payload_available: 1
  payload_not_available: 0

- name: woonkamer-spots
  platform: mqtt
  state_topic: /home/light/woonkamer-spots/relay/0
  command_topic: /home/light/woonkamer-spots/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/woonkamer-spots/status
  payload_available: 1
  payload_not_available: 0

- name: badkamer
  platform: mqtt
  state_topic: /home/light/badkamer/relay/0
  command_topic: /home/light/badkamer/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/light/badkamer/status
  payload_available: 1
  payload_not_available: 0