- platform: yr

- platform: moon

- platform: plex
  name: Plex Spy
  host: rogue.makz.lan
  port: 32400
  username: !secret prive_email
  password: !secret plex_password
  server: MaxFlix

- platform: rfxtrx
  automatic_add: true

- platform: nest
#  monitored_conditions:
#    - 'temperature'
#    - 'humidity'
#    - 'target'
#    - 'operation_mode'
#    - 'weather_temperature'
#    - 'weather_humidity'
#    - 'weather_condition'

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone6"
  name: "Battery MaxiPhone6"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone5"
  name: "Battery MaxiPhone5"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: haveibeenpwned
  email:
    - !secret prive_email
    - !secret prive_email2
    - !secret work_emailA

- platform: nzbget
  host: !secret nzbget_host
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - article_cache
    - average_download_rate
    - download_paused
    - download_rate
    - download_size
    - free_disk_space
    - post_paused
    - remaining_size
    - uptime

- platform: openweathermap
  api_key: !secret owm_api_key
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow

- platform: api_streams

- platform: darksky
  api_key: !secret dark_sky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance

