- platform: yr

- platform: moon

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: plex
  name: Plex Spy
  host: rogue.makz.lan
  port: 32400
  username: !secret prive_email
  password: !secret plex_password
  server: MaxFlix

- platform: rfxtrx
  automatic_add: false

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone6"
  name: "Battery MaxiPhone6"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone5"
  name: "Battery MaxiPhone5"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

# - platform: api_streams

#- platform: darksky
#  api_key: !secret dark_sky_api
#  update_interval: '00:05'
#  monitored_conditions:
#    - summary
#    - icon
#    - nearest_storm_distance
#    - nearest_storm_bearing
#    - precip_type
#    - precip_intensity
#    - precip_probability
#    - temperature
#    - apparent_temperature
#    - dew_point
#    - wind_speed
#    - wind_bearing
#    - cloud_cover
#    - humidity
#    - pressure
#    - visibility
#    - ozone
#    - minutely_summary
#    - hourly_summary
#    - daily_summary
#    - temperature_max
#    - temperature_min
#    - apparent_temperature_max
#    - apparent_temperature_min
#    - precip_intensity_max
