- platform: yr

- platform: moon

- platform: time_date
  display_options:
    - 'time'

- platform: plex
  name: Plex Spy
  host: rogue.makz.lan
  port: 32400
  username: !secret prive_email
  password: !secret plex_password
  server: MaxFlix

- platform: rfxtrx
  automatic_add: true

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone6"
  name: "Battery MaxiPhone6"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/makzdot/maxiphone5"
  name: "Battery MaxiPhone5"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: nzbget
  host: !secret nzbget_host
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - article_cache
    - average_download_rate
    - download_paused
    - download_rate
    - download_size
    - free_disk_space
    - post_paused
    - remaining_size
    - uptime

- platform: openweathermap
  api_key: !secret owm_api_key
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow

# - platform: api_streams

- platform: darksky
  api_key: !secret dark_sky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max

- platform: template
  sensors:
    auto_light_start:
      friendly_name: 'Lights on at'
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_slider.auto_light_minutes") | int)  * 60)  | timestamp_custom("%H:%M") }}'
      entity_id:
        - sun.sun
        - input_slider.auto_light_minutes
    auto_light_stop:
      friendly_name: 'Lights out at'
      value_template: '{{ ( as_timestamp(states.sun.sun.attributes.next_setting) + (states("input_slider.auto_light_minutes") | int)  * 60 + (states("input_slider.auto_light_duration") | float) * 60 * 60  )  | timestamp_custom("%H:%M") }}'
      entity_id:
        - sun.sun
        - input_slider.auto_light_minutes
        - input_slider.auto_light_duration
    auto_light_minutes:
      friendly_name: 'Lights on '
      value_template: '{{ "%d minutes after sunset" | format(states("input_slider.auto_light_minutes") | int) }}'
      entity_id:
        - input_slider.auto_light_minutes
    auto_light_duration:
      friendly_name: 'Lights on for'
      value_template: '{{ "%0.1f hours" | format(states("input_slider.auto_light_duration") | float) }}'
      entity_id:
        - input_slider.auto_light_duration
