- platform: rfxtrx
  automatic_add: false
  devices:
    0b110000011acf1604010f70:
      name: Zonnescherm
    0b11000b011acf1609010f70:
      name: Main Switch
      fire_event: True

- platform: flux
  name: Fluxer
  lights:
    - light.eettafel
  brightness: 35
  start_time: '7:00'
  stop_time: '23:59'
  start_colortemp: 5000
  sunset_colortemp: 4000
  stop_colortemp: 2700

