- platform: rfxtrx
  automatic_add: True
  devices:
    0b110000011acf1604010f70:
      name: Zonnescherm
    0b110000015e25460a010f70:
      name: Bewegingsensor gang
      fire_event: true
    0b1100010131a3ce0a010f60:
      name: Schakelaar Badkamer
      fire_event: true
    0b11000b011acf1609010f70:
      name: Main Switch
      fire_event: True