- platform: rfxtrx
  automatic_add: false
  devices:
    0b110000011acf1604010f70:
      name: Zonnescherm
    0b11000b011acf1609010f70:
      name: Main Switch
      fire_event: True

- platform: flux
  lights:
    - light.eettafel
  name: Fluxer
  start_time: '06:30'
  stop_time: '23:59'
  start_colortemp: 4000
  sunset_colortemp: 2800
  stop_colortemp: 2700
  disable_brightness_adjust: False
  mode: mired
