- platform: rfxtrx
  automatic_add: true
  devices:
    0b110000011acf1604010f70:
      name: Zonnescherm
    0b11000b011acf1609010f70:
      name: Main Switch
      fire_event: True
    0b110001011acf160a000070:
      name: Test Switch
      fire_event: true
    0b110034011acf160b000070:
      name: Test eettafel
      fire_event: true
    0b110000015e25460a010f70:
      name: Bewegingsensor gang
      fire_event: true

- platform: flux
  lights:
    - light.eettafel
    - light.keukenlamp_1
    - light.keukenlamp_2
    - light.keukenlamp_3
    - light.keukenlamp_4
    - light.keukenlamp_5
    - light.keukenlamp_6
    - light.keukenlamp_7
    - light.keukenlamp_8
  name: Fluxer
  start_time: '06:30'
  stop_time: '23:59'
  start_colortemp: 5000
  sunset_colortemp: 2800
  stop_colortemp: 2500
  disable_brightness_adjust: False
  brightness: 60
  mode: mired
