- platform: rfxtrx
  automatic_add: false
  devices:
    0b11000001b40efe0a000070:
    # 0b110000011acf1604010f70:
      name: Zonnescherm
    0b110000015e25460a010f70:
      name: Bewegingsensor gang
      # fire_event: true
    0b1100010131a3ce0a010f60:
      name: Schakelaar Badkamer
      # fire_event: true
    0b11000b011acf1609010f70:
      name: Main Switch
      # fire_event: True

- name: woonkamer-tvmeubel
  platform: mqtt
  state_topic: /home/switch/woonkamer-tvmeubel/relay/0
  command_topic: /home/switch/woonkamer-tvmeubel/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: /home/switch/woonkamer-tvmeubel/status
  payload_available: 1
  payload_not_available: 0