title: Makzdots Home
views:
  - icon: mdi:home-assistant
    title: Woonkamer
    cards:

      - type: entity-filter
        entities:
          - device_tracker.makzdot_max
          - device_tracker.rikkert_rikki
          - device_tracker.a010818e6c32
          - device_tracker.9097f3588eb4
        state_filter:
          - 'home'
        card:
          type: glance
          title: Mensen thuis

      - type: picture-elements
        # title: Casa di Maxi
        image: https://raw.githubusercontent.com/makzdot/diagrams/master/Floorplan%20Casa%20di%20Maxi.png
        elements:
          - type: service-button
            title: Alle lichten uit
            style:
              top: 99%
              left: 80%
            service: light.turn_off
            service_data:
                entity_id: group.
          - type: state-icon
            entity: light.schemerlamp_noeri
            tap_action: toggle
            style:
              top: 2%
              left: 6%
          - type: state-icon
            entity: light.noeri
            tap_action: toggle
            style:
              top: 12%
              left: 22%
          - type: state-icon
            entity: input_boolean.noeri_slaapt
            tap_action: toggle
            style:
              top: 18%
              left: 10%
          - type: state-icon
            entity: light.schemerlamp_max
            tap_action: toggle
            style:
              top: 7%
              left: 90%
          - type: state-icon
            entity: light.plafoniere_max
            tap_action: toggle
            style:
              top: 17%
              left: 55%
          - type: state-icon
            entity: light.badkamer
            tap_action: toggle
            style:
              top: 45%
              left: 70%
          - type: state-icon
            entity: light.hallamp_1
            tap_action: toggle
            style:
              top: 55%
              left: 25%
          - type: state-icon
            entity: light.hallamp_2
            tap_action: toggle
            style:
              top: 60%
              left: 25%
          - type: state-icon
            entity: light.hallamp_3
            tap_action: toggle
            style:
              top: 65%
              left: 25%
          - type: state-icon
            entity: light.hallamp_4
            tap_action: toggle
            style:
              top: 45%
              left: 25%
          - type: state-icon
            entity: switch.bewegingsensor_gang
            tap_action: toggle
            style:
              top: 26%
              left: 25%
          - type: state-icon
            entity: light.woonkamer_groep_1
            tap_action: toggle
            style:
              top: 85%
              left: 20%
          - type: state-icon
            entity: light.woonkamer_1
            tap_action: toggle
            style:
              top: 80%
              left: 20%
          - type: state-icon
            entity: light.keukenverlichting_groep_1
            tap_action: toggle
            style:
              top: 63%
              left: 55%
          - type: state-icon
            entity: light.keukenverlichting_groep_2
            tap_action: toggle
            style:
              top: 63%
              left: 60%



      - type: entities
        title: Schakelaars
        entities:
          - switch.main_switch
          - switch.zonnescherm

      - type: picture-entity
        entity: camera.woonkamercam

      - type: media-control
        entity: media_player.woonkamer_appletv

      - type: media-control
        entity: media_player.woonkamer_tv

  - icon: mdi:hotel
    title: Slaapkamers
    cards:

        - type: entities
          title: Wekker
          entities:
            - input_boolean.wekker_aan_uit
            - input_datetime.wektijd
            - binary_sensor.workday_sensor

        - type: entities
          title: Slaapkamer Max
          entities:
            - light.plafoniere_max
            - light.schemerlamp_max

        - type: entities
          title: Slaapkamer Noeri
          entities:
            - light.schemerlamp_noeri
            - light.hanglamp_noeri

        - type: entities
          title: Hal
          entities:
            - light.hallamp_1
            - light.hallamp_2
            - light.hallamp_3
            - light.hallamp_4
            - switch.bewegingsensor_gang
            - input_boolean.noeri_slaapt

        - type: entities
          title: Hal automations
          entities:
            - automation.hal_aan
            - automation.hal_uit

        - type: entities
          title: Badkamer
          entities:
            - switch.sonoff_badkamer
            - switch.schakelaar_badkamer

  - icon: mdi:gauge
    title: Sensors
    cards:

      - type: entities
        title: Datum en Tijd
        entities:
          - sensor.time
          - binary_sensor.workday_sensor
          - sun.sun
          - sensor.moon

      - type: entity-filter
        filter:
          - entity_id: 'binary_sensor.living_room_thermostat*'
            state: 'on'
        card_config:
          title: Nest Thermostaat status

      - type: entity-filter
        filter:
          - entity_id: 'sensor.living_room_thermostat*'
        card_config:
          title: Nest Thermostaat

      - type: history-graph
        entity: history_graph.recent_switches

      - type: entity-filter
        filter:
          - entity_id: '*_nest_protect_*'
        card_config:
          title: Nest Protects

      - type: entity-filter
        filter:
          - entity_id: 'sensor.afstandsbediening*'
        card_config:
          title: Battery afstandsbedieningen

      - type: entity-filter
        filter:
          - domain: device_tracker
        card_config:
          title: Alle device trackers

  - icon: mdi:play-circle-outline
    title: Media players
    cards:
      - type: entities
        entities:
          - sensor.plex
      - type: entity-filter
        filter:
          - entity_id: 'media_player.*'
        card_config:
          title: Media Players

