title: Makzdots Home
views:
  - icon: mdi:home-assistant
    title: Woonkamer
    cards:

      - type: entity-filter
        entities:
          - device_tracker.makzdot_max
          - device_tracker.rikkert_rikki
          - device_tracker.1c232c46cb0d
          - device_tracker.9097f3588eb4
        state_filter:
          - 'home'
        card:
          type: glance
          title: Mensen thuis

      - type: entities
        title: Woonkamer scenes
        entities:
          - scene.woonkamer_sfeerverlichting
          - scene.woonkamer_bioscoop
          - scene.afwezig
          - scene.alle_lichten_uit
          - scene.schoonmaak

      - type: entities
        title: Woonkamer verlichting
        entities:
          - light.woonkamerschemerlamplinks
          - light.woonkamerschemerlamprechts
          - light.woonkamerspots
          - light.woonkamer_groep_1
          - light.woonkamer_1
          - light.keukenverlichting_groep_1
          - light.keukenverlichting_groep_2

      - type: entities
        title: RGB Led verlichting
        entities:
          - light.woonkamerledstrip3
          - light.woonkamerledstriptv
          - light.woonkamerledstriptvmeubel
          - light.eettafel

      - type: entities
        title: Schakelaars
        entities:
          - switch.woonkamertvmeubel
          - switch.main_switch
          - switch.zonnescherm

      - type: entities
        entities:
          - climate.living_room_thermostaat

      - type: entity-filter
        entities:
          - binary_sensor.living_room_thermostat_thermostaat_fan
          - binary_sensor.living_room_thermostat_thermostaat_has_leaf
          - binary_sensor.living_room_thermostat_thermostaat_is_locked
          - binary_sensor.living_room_thermostat_thermostaat_is_using_emergency_heat
          - binary_sensor.living_room_thermostat_thermostaat_online
        state_filter:
          - 'on'
        card:
          title: Thermostaat status

      - type: picture-entity
        entity: camera.woonkamercam

      - type: media-control
        entity: media_player.woonkamer

      - type: media-control
        entity: media_player.woonkamer_tv

  - icon: mdi:map
    title: Plattegronden
    cards:
      - type: picture-elements
        image: https://raw.githubusercontent.com/makzdot/diagrams/master/Floorplan%20Casa%20di%20Maxi-Floorplan%20woonkamer.png
        elements:
          - type: state-icon
            entity: light.hallamp_1
            tap_action: toggle
            style:
              top: 10%
              left: 25%
          - type: state-icon
            entity: light.hallamp_2
            tap_action: toggle
            style:
              top: 15%
              left: 25%
          - type: state-icon
            entity: light.hallamp_3
            tap_action: toggle
            style:
              top: 20%
              left: 25%
          - type: state-icon
            entity: light.woonkamer_groep_1
            tap_action: toggle
            style:
              top: 70%
              left: 20%
          - type: state-icon
            entity: light.woonkamer_1
            tap_action: toggle
            style:
              top: 60%
              left: 20%
          - type: state-icon
            entity: light.keukenverlichting_groep_1
            tap_action: toggle
            style:
              top: 15%
              left: 55%
          - type: state-icon
            entity: light.keukenverlichting_groep_2
            tap_action: toggle
            style:
              top: 15%
              left: 75%
          - type: state-icon
            entity: light.eettafel
            tap_action: toggle
            style:
              top: 36%
              left: 89%
          - type: state-icon
            entity: climate.living_room_thermostaat
            style:
              top: 38%
              left: 30%
          - type: state-icon
            entity: light.woonkamerschemerlamplinks
            tap_action: toggle
            style:
              top: 52%
              left: 96%
          - type: state-icon
            entity: light.woonkamerschemerlamprechts
            tap_action: toggle
            style:
              top: 81%
              left: 96%
          - type: state-icon
            entity: light.woonkamerspots
            tap_action: toggle
            style:
              top: 87%
              left: 96%
          - type: state-icon
            entity: media_player.woonkamer
            style:
              top: 64%
              left: 95%
          - type: state-icon
            entity: media_player.woonkamer_tv
            style:
              top: 70%
              left: 95%
          - type: state-icon
            entity: light.woonkamerledstrip3
            tap_action: toggle
            style:
              top: 41%
              left: 5%
          - type: state-icon
            entity: light.woonkamerledstriptv
            tap_action: toggle
            style:
              top: 73%
              left: 96%
          - type: state-icon
            entity: light.woonkamerledstriptvmeubel
            tap_action: toggle
            style:
              top: 55%
              left: 96%
          - type: state-icon
            entity: camera.woonkamercam
            style:
              top: 88%
              left: 45%
          - type: state-label
            entity: sensor.living_room_thermostat_thermostaat_temperature
            style:
              top: 50%
              left: 50%
          - type: state-label
            entity: sensor.living_room_thermostat_thermostaat_humidity
            style:
              top: 54%
              left: 50%
          - type: state-label
            entity: sensor.br_temperature
            style:
              top: 94%
              left: 10%
          - type: state-label
            entity: sensor.br_humidity
            style:
              top: 98%
              left: 10%
          - type: state-icon
            entity: switch.zonnescherm
            tap_action: toggle
            style:
              top: 95%
              left: 66%

      - type: picture-elements
        image: https://raw.githubusercontent.com/makzdot/diagrams/master/Floorplan%20Casa%20di%20Maxi-Floorplan%20slaapkamers.png
        elements:
          - type: state-icon
            entity: light.schemerlamp_noeri
            tap_action: toggle
            style:
              top: 5%
              left: 6%
          - type: state-icon
            entity: light.noeri
            tap_action: toggle
            style:
              top: 23%
              left: 22%
          - type: state-icon
            entity: input_boolean.noeri_slaapt
            tap_action: toggle
            style:
              top: 33%
              left: 10%
          - type: state-icon
            entity: light.schemerlamp_max
            tap_action: toggle
            style:
              top: 13%
              left: 90%
          - type: state-icon
            entity: light.plafoniere_max
            tap_action: toggle
            style:
              top: 33%
              left: 55%
          - type: state-icon
            entity: input_boolean.wekker_aan_uit
            tap_action: toggle
            style:
              top: 20%
              left: 95%
          - type: state-icon
            entity: light.badkamer
            tap_action: toggle
            style:
              top: 85%
              left: 68%
          - type: state-icon
            entity: light.hallamp_4
            tap_action: toggle
            style:
              top: 75%
              left: 25%
          - type: state-icon
            entity: switch.bewegingsensor_gang
            tap_action: toggle
            style:
              top: 46%
              left: 25%

  - icon: mdi:hotel
    title: Slaapkamers
    cards:
      - type: entities
        title: Wekker
        entities:
          - input_boolean.wekker_aan_uit
          - input_datetime.wektijd
          - binary_sensor.workday_sensor

      - type: entities
        title: Slaapkamer Max
        entities:
          - light.plafoniere_max
          - light.schemerlamp_max

      - type: entities
        title: Slaapkamer Noeri
        entities:
          - light.schemerlamp_noeri
          - light.hanglamp_noeri

      - type: entities
        title: Hal
        entities:
          - light.hallamp_1
          - light.hallamp_2
          - light.hallamp_3
          - light.hallamp_4
          - switch.bewegingsensor_gang
          - input_boolean.noeri_slaapt

      - type: entities
        title: Hal automations
        entities:
          - automation.hal_aan
          - automation.hal_uit

      - type: entities
        title: Badkamer
        entities:
          - light.badkamer
          - switch.schakelaar_badkamer

  - icon: mdi:gauge
    title: Sensors
    cards:

      - type: entities
        title: Personen
        entities:
          - group.personen
          - group.schoonmaak

      - type: entities
        title: Datum en Tijd
        entities:
          - sensor.time
          - binary_sensor.workday_sensor
          - sun.sun
          - sensor.moon

      - type: entities
        title: Afstand tot huis
        entities:
          - proximity.home

      - type: weather-forecast
        entity: weather.dark_sky

      - type: glance
        title: Nest Protect Gang
        entities:
          - binary_sensor.hallway_nest_protect_online
          - sensor.hallway_nest_protect_battery_health
          - sensor.hallway_nest_protect_co_status
          - sensor.hallway_nest_protect_smoke_status
          - sensor.hallway_nest_protect_color_status

      - type: map
        title: Where the hell is Max
        entities:
          - device_tracker.makzdot_max
          - zone.home
          - zone.surfnet

  - icon: mdi:play-circle-outline
    title: Media players
    cards:
      - type: entities
        entities:
          - sensor.plex

      - type: media-control
        entity: media_player.woonkamer

      - type: media-control
        entity: media_player.woonkamer_tv

      - type: media-control
        entity: media_player.plex_woonkamer

