name: My Awesome Home
views:
    # The name of a view will be used as tab title.
    # Might be used for other things in the future.
  - name: Test
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    #theme: dark-mode
    # The cards to show on this view.
    cards:
        # The entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        entities:
          - binary_sensor.living_room_thermostat_thermostaat_online
          - binary_sensor.living_room_thermostat_thermostaat_has_leaf
          - binary_sensor.living_room_thermostat_thermostaat_is_locked
          - binary_sensor.living_room_thermostat_thermostaat_is_using_emergency_heat
          - binary_sensor.living_room_thermostat_thermostaat_fan

        # The filter card will filter available entities for certain criteria
        # and render it as type 'entities'.
      - type: entity-filter
        # Filter criteria. They are all optional.
        filter:
          domain: input_boolean
          state: 'on'
        # This config will be passed to the card rendering the filter results
        card_config:
          title: Input booleans that are on