title: Makzdots Home
views:
  - tab_icon: mdi:home-assistant
    name: Woonkamer
    cards:
    - type: entity-filter
      filter:
        - entity_id: 'device_tracker.makzdot_max_iphone6s'
          state: 'home'
        - entity_id: device_tracker.1c232c46cb0d
          state: 'home'
        - entity_id: device_tracker.9097f3588eb4
          state: 'home'
        - entity_id: device_tracker.a010818e6c32
          state: 'home'
        - entity_id:  device_tracker.rikkert_rikki
          state: 'home'
      card: glance
      card_config:
        title: Mensen thuis

    - type: entity-filter
      filter:
        - entity_id: 'scene.*'
      card_config:
        title: Scenes

    - type: entity-filter
      filter:
        - entity_id: climate.living_room_thermostaat
        - entity_id: 'binary_sensor.living_room_thermostat*'
          state: 'on'

    - type: entity-filter
      filter:
        - entity_id: 'light.keukenverlichting_groep*'
      card_config:
        title: Keukenverlighting

    - type: entities
      title: Woonkamerverlichting
      entities:
        - light.lifx_light_03bec2
        - light.woonkamer_1
        - light.woonkamer_groep_1
        - switch.sonoff_basic_076e52
        - switch.espurna_076a50
        - switch.wkschemerlamprechts

    - type: entity-filter
      filter:
        - entity_id: 'light.h801*'
      card_config:
        title: LED strips

    - type: entities
      title: Schakelaars
      entities:
        - switch.main_switch
        - switch.zonnescherm

    - type: camera-preview
      entity: camera.woonkamercam

    - type: media-control
      entity: media_player.woonkamer_appletv_2

    - type: media-control
      entity: media_player.woonkamer_tv

  - tab_icon: mdi:hotel
    name: Slaapkamers
    cards:
      - type: entities
        title: Wekker
        entities:
          - input_boolean.wekker_aan_uit
          - input_datetime.wektijd
          - binary_sensor.workday_sensor

  - tab_icon: mdi:gauge
    name: Sensors
    cards:

    - type: entities
      title: Datum en Tijd
      entities:
        - sensor.time
        - binary_sensor.workday_sensor
        - sun.sun
        - sensor.moon

    - type: entity-filter
      filter:
        - entity_id: 'binary_sensor.living_room_thermostat*'
          state: 'on'
      card_config:
        title: Nest Thermostaat status

    - type: entity-filter
      filter:
        - entity_id: 'sensor.living_room_thermostat*'
      card_config:
        title: Nest Thermostaat

    - type: history-graph
      entity: history_graph.recent_switches

    - type: entity-filter
      filter:
        - entity_id: '*_nest_protect_*'
      card_config:
        title: Nest Protects

    - type: entity-filter
      filter:
        - entity_id: 'sensor.afstandsbediening*'
      card_config:
        title: Battery afstandsbedieningen


