title: Makzdots Home
views:
  - tab_icon: mdi:home-assistant
    name: Blah
    cards:
    - type: entity-filter
      filter:
        - domain: device_tracker
          state: 'home'
        - entity_id: 'device_tracker.makzdot*'
      card: glance
      card_config:
        title: People at home