- alias: 'TV aan'
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_tv
      from: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.woonkamer

- alias: 'TV uit'
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_tv
      to: 'off'
  action:
    - service: media_player.turn_off
      entity_id: media_player.woonkamer

