- alias: 'Licht aan bij thuiskomst'
  trigger:
    platform: state
    entity_id: group.personen
    to: home
  condition:
    condition: sun
    after: 'sunset'
    after_offset: "-1:20:00"
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_sfeerverlichting

- alias: 'Licht aan in de avond'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:20:00"
  condition:
    condition: state
    entity_id: group.personen
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.woonkamer_sfeerverlichting

- alias: 'Licht aan voor schoonmaker'
  trigger:
    platform: state
    entity_id: group.schoonmaak
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: "09:00:00"
        before: "17:30:00"
      - condition: state
        entity_id: group.personen
        state: 'not_home'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.schoonmaak
    - service: notify.ios_maxiphonesix
      data:
        message: “Dagmar en Ingeborg arriveren”
        data:
          push:
            sound: "US-EN-Morgan-Freeman-Friend-Is-Arriving.wav"

- alias: 'Bewoners verlaten huis'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.schoonmaak
        state: 'not_home'
      - condition: state
        entity_id: group.schoonmaak
        state: 'unknown'        
  action:
    - service: scene.turn_on
      entity_id: scene.afwezig
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room_thermostaat
        away_mode: true

- alias: 'Schoonmaak verlaat huis'
  trigger:
    platform: state
    entity_id: group.schoonmaak
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: group.personen
    state: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.afwezig
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room_thermostaat
        away_mode: true
    - service: notify.ios_maxiphonesix
      data:
        message: “Dagmar en Ingeborg zijn vertrokken”
        data:
          push:
            sound: "US-EN-Morgan-Freeman-Turning-Off-The-Lights.wav"
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room_thermostaat
        away_mode: true

- alias: 'Thermostaat uit Away mode bij thuiskomst'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'not_home'
    to: 'home'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room_thermostaat
        away_mode: false
