- alias: 'Away'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.away
#    - service: notify.telegram
#      data:
#        message: House is in away mode!