- alias: 'Away'
  trigger:
    platform: state
    entity_id: group.all_tracked
    from: 'home'
    to: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.away
    - service: climate.set_away_mode
      data:
        entity_id: climate.living_room_thermostaat
        away_mode: 'off'
