- alias: 'Away'
  trigger:
    - platform: state
      entity_id: group.personen
      from: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.schoonmakers
      state: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.away