- alias: 'Badkamer aan'
  trigger:
    - platform: state
      entity_id: light.badkamer
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.schakelaar_badkamer
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.badkamer
    - service: switch.turn_on
      entity_id: switch.schakelaar_badkamer

- alias: 'Badkamer uit'
  trigger:
    - platform: state
      entity_id: light.badkamer
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.schakelaar_badkamer
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.badkamer
    - service: switch.turn_off
      entity_id: switch.schakelaar_badkamer
