- alias: 'Badkamer aan'
  trigger:
    - platform: state
      entity_id: switch.sonoff_badkamer
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.schakelaar_badkamer
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_badkamer
    - service: switch.turn_on
      entity_id: switch.schakelaar_badkamer

- alias: 'Badkamer uit'
  trigger:
    - platform: state
      entity_id: switch.sonoff_badkamer
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.schakelaar_badkamer
      from: 'on'
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_badkamer
    - service: switch.turn_off
      entity_id: switch.schakelaar_badkamer
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "This is a test."
