- alias: "Owntracks Refresh"
  trigger:
    - platform: time
      minutes: '/30'
      seconds: 0
  action:
    - service: mqtt.publish
      data:
        topic: "owntracks/rikkert/rikki/cmd"
        payload_template: '{"_type": "cmd","action": "reportLocation"}'