- alias: Test flash
  trigger:
    - platform: state
      entity_id: switch.test_switch
      to: 'on'
  action:
#    - service: scene.turn_on
#      entity_id: scene.Schoonmaken
    - service: light.turn_on
      data:
        entity_id:
          - light.led_strip
          - light.led_strip_2
        brightness: 255
        color_name: red
        flash: long
    - service: script.red_alert

