- alias: Red Alert
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.schoonmaak
      state: 'not_home'
    - condition: state
      entity_id: group.personen
      state: 'not_home'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.led_strip
          - light.led_strip_2
          - light.led_strip_3
        brightness: 255
        color_name: red
        flash: long
    - service: light.lifx_effect_pulse
      data:
        brightness: 255
        color_name: red
        cycles: 120
        entity_id: light.eettafel
        mode: breathe
        period: 1
    - service: notify.facebook
      data:
        message: 'Good Evening'
        target:
          - 0031651541739
