- alias: 'Hal aan'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: group.personen
      state: 'home'
    - condition: state
      entity_id: group.schoonmaak
      state: 'home'
  action:
    - service: light.turn_on
      entity_id:
        - light.hallamp_2
      data:
        brightness: 50
        color_temp: 460
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.noeri_slaapt
          state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: light.woonkamerledstriptvmeubel
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
    - service: light.turn_on
      entity_id:
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3
        - light.hallamp_4
      data:
        brightness: 140
        color_temp: 460


- alias: 'Hal uit'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3
        - light.hallamp_4

- alias: 'Switch off in the morning'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.noeri_slaapt