- alias: 'Hal aan'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.hallamp_2
      data:
        brightness: 50
        color_temp: 460
    - condition: or
      conditions:
        - condition: state
          entity_id: light.h801_995008
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
    - service: light.turn_on
      entity_id:
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3
        - light.hallamp_4
      data:
        brightness: 140
        color_temp: 460


- alias: 'Hal uit'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3
        - light.hallamp_4