- alias: 'Hal aan'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang 
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: 
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3
      data:
        brightness: 140
        color_temp: 460

- alias: 'Hal uit'
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.hallamp_1
        - light.hallamp_2
        - light.hallamp_3