- alias: Hal light motion on night before sunrise
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.keukenlamp_3
      state: 'off'
    - condition: sun
      before: 'sunrise'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hal
        brightness: 30

- alias: Hal light motion on full night before sunrise
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.keukenlamp_3
      state: 'on'
    - condition: sun
      before: 'sunrise'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hal
        brightness: 255

- alias: Hal light motion on night after sunset
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.keukenlamp_3
      state: 'off'
    - condition: sun
      after: 'sunset'
      offset: "-01:20:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hal
        brightness: 30

- alias: Hal light motion on
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.keukenlamp_3
      state: 'on'
    - condition: sun
      after: 'sunset'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hal
        brightness: 255

- alias: Hal light motion off
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hal
