- alias: Hal light motion at night
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.personen
          state: home
        - condition: or
          conditions:
            - condition: sun
              before: 'sunrise'
            - condition: sun
              after: 'sunset'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hallamp_2
        brightness: 3
        color_temp: 457

- alias: Hal light motion at daytime
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.personen
          state: home
        - condition: or
          conditions:
            - condition: sun
              before: 'sunset'
            - condition: sun
              after: 'sunrise'
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.hallamp_4
        brightness: 200
    - service: light.turn_on
      data:
        entity_id:
          - light.hallamp_1
          - light.hallamp_2
          - light.hallamp_3
        brightness: 200
        color_temp: 457


- alias: Hal light motion off
  trigger:
    platform: state
    entity_id: switch.bewegingsensor_gang
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hallamp_4
          - light.hallamp_1
          - light.hallamp_2
          - light.hallamp_3
