- alias: Hal light motion on
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      to: 'on'
  condition:
    conditions:
      - condition: state
        entity_id: light.keukenlamp_3
        state: off
      - condition: sun
        after: 'sunset'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hal
        brightness: 30

- alias: Hal light motion off
  trigger:
    - platform: state
      entity_id: switch.bewegingsensor_gang
      to: 'off'
  condition:
    conditions:
      - condition: state
        entity_id: light.keukenlamp_3
        state: off
      - condition: sun
        after: 'sunset'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hal
