- alias: Schoonmaak arriveerd
  trigger:
    platform: state
    entity_id: group.schoonmaak
    from: 'not_home'
    to: 'home'
  action:
    service: notify.ios_maxiphonesix
    data:
      message: "Dagmar en Ingeborg zijn gearriveerd."
      data:
        push:
          badge: 1

- alias: Schoonmaak vertrokken
  trigger:
    platform: state
    entity_id: group.schoonmaak
    from: 'home'
    to: 'not_home'
  action:
    service: notify.ios_maxiphonesix
    data:
      message: "Dagmar en Ingeborg zijn vertrokken."
      data:
        push:
          badge: 1
