- alias: 'Licht aan bij thuiskomst'
  trigger:
    platform: state
    entity_id: group.personen
    to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
    offset: "-01:20:00"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

