- alias: 'Licht aan bij thuiskomst'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
    # Optional offset value
    after_offset: "-1:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal


#  condition:
#    condition: sun
#    after: sunset
#    after_offset: "-01:20:00"
