- alias: 'Licht aan met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.main_switch
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

- alias: 'Licht uit met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.main_switch
    to: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.alle_lichten_uit

- alias: 'badkamer aan met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_switch
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.schemerlamp_noeri
      - light.schemerlamp_max

- alias: 'Badkamer uit met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_switch
    to: 'off'
  action:
    service: light.turn_off
    entity_id:
      - light.schemerlamp_noeri
      - light.schemerlamp_max

- alias: 'Eettafel aan met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_eettfel
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.eettafel

- alias: 'Eettafel uit met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_eettafel
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.eettafel
