- alias: 'Licht aan met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.main_switch
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

- alias: 'Licht uit met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.main_switch
    to: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.alle_lichten_uit

- alias: 'schemerlampen wooonkamer aan met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_switch
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.schemerlamp_noeri
      - light.schemerlamp_max

- alias: 'schemerlampen wooonkamer uit met afstandsbediening'
  trigger:
    platform: state
    entity_id: switch.test_switch
    to: 'off'
  action:
    service: light.turn_off
    entity_id:
      - light.schemerlamp_noeri
      - light.schemerlamp_max

- alias: 'Verander status van schakelaar als schemerlamp aan gaat'
  trigger:
    platform: state
    entity_id: light.schemerlamp_noeri
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.test_switch

- alias: 'Verander status van schakelaar als schemerlamp uit gaat'
  trigger:
    platform: state
    entity_id: light.schemerlamp_noeri
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.test_switch
