- alias: 'Licht aan voor schoonmaker'
  trigger:
    platform: state
    entity_id: group.schoonmaak
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: time
      after: "09:00:00"
      before: "17:30:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.personen
      state: 'not_home'
  action:
      service: scene.turn_on
      entity_id: scene.schoonmaken
