- alias: 'Licht aan bij thuiskomst'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

