- alias: 'Licht aan in de avond'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:20:00"
  condition:
    condition: state
    entity_id: group.personen
    state: home
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal