- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      from: 'playing'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: 'sunset'
        after_offset: '-1:20:00'
      - condition: sun
        before: 'sunrise'
        before_offset: "1:20:00"
  action:
    - delay: '0:00:07'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.woonkamer_appletv
        state: 'paused'
      - condition: state
        entity_id: media_player.woonkamer_appletv
        state: 'idle'
      - condition: state
        entity_id: media_player.woonkamer_appletv
        state: 'off'
    - service: scene.turn_on
      entity_id: scene.livingroom_normal


- alias: "Media player playing Movie"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      from: 'paused'
      to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.media_player.woonkamer_appletv.attributes.media_content_type == "movie" }}'
    - condition: or
      conditions:
      - condition: sun
        before: 'sunrise'
        before_offset: "1:20:00"
      - condition: sun
        after: 'sunset'
        after_offset: "-1:20:00"
  action:
    - delay: '0:00:02'
    - service: scene.turn_on
      entity_id: scene.livingroom_dim


- alias: "Media player playing TVshow"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.media_player.woonkamer_appletv.attributes.media_content_type == "tvshow" }}'
    - condition: or
      conditions:
      - condition: sun
        before: 'sunrise'
        before_offset: "1:20:00"
      - condition: sun
        after: 'sunset'
        after_offset: "-1:20:00"
  action:
    - delay: '0:00:02'
    - service: scene.turn_on
      entity_id: scene.livingroom_dim