- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      from: 'playing'
      to: 'paused'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      - service: scene.turn_on
        entity_id: scene.livingroom_normal
      - service: notify.telegram
        message: "AppleTV Paused"
