- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      from: 'playing'
      to: 'paused'
  condition:
    - condition: sun
      after: 'sunset'
      after_offset: '-1:20:00'
  action:
    - delay: '0:00:10'
    - service: scene.turn_on
      entity_id: scene.livingroom_normal

#    - service: notify.telegram
#      data:
#        message: "AppleTV Paused"
