- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.apple_tv
      state: 'playing'
      for:
        hours: 0
        minutes: 0
        seconds: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim
