- alias: "Media player playing Movie"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      state: 'playing'
  condition:
    - condition: sun
      after: 'sunset'
      after_offset: '-1:20:00'
    - condition: template
      value_template: '{{ states.media_player.woonkamer_appletv.attributes.media_content_type == "movie" }}'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim
    - delay: 0:10
#    - service: notify.telegram
#      data:
#        message: "AppleTV Playing movie"

- alias: "Media player playing TVshow"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer_appletv
      state: 'playing'
  condition:
    - condition: sun
      after: 'sunset'
      after_offset: '-1:20:00'
    - condition: template
      value_template: '{{ states.media_player.woonkamer_appletv.attributes.media_content_type == "tvshow" }}'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim
    - delay: 0:10
#    - service: notify.telegram
#      data:
#        message: "AppleTV Playing tvshow"
