- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer
      from: 'playing'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: 'sunset'
        after_offset: '-1:20:00'
      - condition: sun
        before: 'sunrise'
        before_offset: "-1:20:00"
  action:
    - delay: '0:00:07'
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.woonkamer
        state: 'paused'
      - condition: state
        entity_id: media_player.woonkamer
        state: 'idle'
      - condition: state
        entity_id: media_player.woonkamer
        state: 'off'
    - service: scene.turn_on
      entity_id: scene.woonkamer_sfeerverlichting


- alias: "Media player playing Movie"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer
      to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.media_player.woonkamer.attributes.media_content_type == "video" }}'
    - condition: or
      conditions:
      - condition: sun
        before: 'sunrise'
        before_offset: "-1:20:00"
      - condition: sun
        after: 'sunset'
        after_offset: "-1:20:00"
  action:
    - delay: '0:00:02'
    - service: scene.turn_on
      entity_id: scene.woonkamer_bioscoop


- alias: "Media player playing TVshow"
  trigger:
    - platform: state
      entity_id: media_player.woonkamer
      to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ states.media_player.woonkamer.attributes.media_content_type == "video" }}'
    - condition: or
      conditions:
      - condition: sun
        before: 'sunrise'
        before_offset: "-1:20:00"
      - condition: sun
        after: 'sunset'
        after_offset: "-1:20:00"
  action:
    - delay: '0:00:02'
    - service: scene.turn_on
      entity_id: scene.woonkamer_bioscoop