trigger:
  platform: template
  value_template: '{{ states.sensor.time.state == (states.input_datetime.wektijd.attributes.timestamp | int | timestamp_custom("%H:%M", False)) }}'
action:
  service: light.turn_on
  entity_id: light.h801_9950fc