- alias: "Zonnescherm inrollen"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.azimuth }}"
    above: 298.0
  action:
    service: switch.turn_off
    entity_id: switch.zonnescherm