- alias: "Zonnescherm inrollen wanneer de zon wegdraait"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.azimuth }}"
    above: 200.0
    below: 201.0
  action:
    service: switch.turn_off
    entity_id: switch.zonnescherm

- alias: "Zonnescherm inrollen bij regen"
  trigger:
    platform: numeric_state
    entity_id: sensor.br_precipitation
    above: 0.0
  action:
    service: switch.turn_off
    entity_id: switch.zonnescherm
